
project_id = "gwmygthanyycveyqqspr"

[functions.steam-auth]
verify_jwt = false

[functions.handle-stripe-donation]
verify_jwt = false

[functions.fetch-hltb-estimate]
verify_jwt = true

[functions.backfill-hltb-estimates]
verify_jwt = true

[functions.refresh-game-price]
verify_jwt = true
