
project_id = "gwmygthanyycveyqqspr"

[api]
  enabled = true
  port = 54321
  schemas = ["public", "storage", "graphql_public"]

[db]
  port = 54322

[studio]
  enabled = true
  port = 54323
  
[inbucket]
  enabled = true
  port = 54324

[storage]
  enabled = true
  
[auth]
  enabled = true
  
[realtime]
  enabled = true

[functions.get-queue-stats-by-status]
  verify_jwt = true

[functions.fetch-steam-app-details]
  verify_jwt = true
